# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r: bioc-release
cache: packages
sudo: true
dist: trusty

addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

r_packages:
  - rmarkdown
  - covr
  - testthat

bioc_packages:
  - BiocInstaller
  - graph
  - RBGL
  - Rgraphviz

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e "capabilities()"
