# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true
dist: trusty

addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

r_packages:
  - rmarkdown
  - covr
##   - decisionSupport
##   - ggplot2
##   - gRain
  - bnlearn
  - testthat
##  - qpdf
##   - fitdistrplus
##   - rriskDistributions

bioc_packages:
  - BiocInstaller
  - graph
  - RBGL
  - Rgraphviz

##   install:
##   - R -e 'source("http://bioconductor.org/biocLite.R"); biocLite(c("graph","RBGL","Rgraphviz"))'
##   - R -e 'install.packages(c("rmarkdown", "decisionSupport", "ggplot2", "gRain", "bnlearn", "testthat", "fitdistrplus", "rriskDistributions"), dependencies = T)'
##   - R -e 'install_url ("https://cran.r-project.org/src/contrib/Archive/tcltk/tcltk_0.1-1.tar.gz")'
##   - wget https://cran.r-project.org/src/contrib/Archive/tcltk/tcltk_0.1-1.tar.gz -O /tmp/tcltk_0.1-1.tar.gz
##   - tar -xzvf tcltk_0.1-1.tar.gz
##   - pushd tcltk_0.1-1 && ./configure --prefix=/usr && make && sudo make install && popd
##   - R -e 'install.packages ("/tmp/tcltk_0.1-1.tar.gz", type = "source")'
Rscript -e "capabilities()"
after_success:
  - Rscript -e 'library(covr); codecov()'
