# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - release
dist: bionic
sudo: required
cache: packages
services:
  - xvfb
addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

r_packages:
  - testthat
  - knitr
  - rmarkdown
  - covr
script:
  - R CMD build .
  - travis_wait 50 R CMD check *tar.gz --as-cran
after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e "capabilities()"
