# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - release
cache: packages
services:
  - xvfb
addons:
  apt:
    packages:
      - tcl8.5-dev
      - tk8.5-dev

install: travis_wait 20 mvn install

before_install:
  - export DISPLAY=:99.0

r_packages:
  - testthat
  - knitr
  - rmarkdown
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e "capabilities()"
