# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
#  - C:\RLibrary
  - packages -> appveyor.yml

# Adapt as necessary starting from here

environment:
  R_VERSION: release
  USE_RTOOLS: yes
  _R_CHECK_FORCE_SUGGESTS_: false

r_packages:
  - decisionSupport
  - fitdistrplus
  - grid
  - gridExtra
  - ggplot2
  - scales
  - reshape2
  - graph
  - Rgraphviz
  - gRain
  - bnlearn
  - rriskDistributions
  - plyr
  - methods
  - testthat
  - knitr
  - rmarkdown
  - covr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
